services:
  harvesterai:
    image: dphip/harvesterai:latest
    ports:
      - "7860:7860"
    volumes:
      - harvesterai_data:/data
    restart: unless-stopped
    environment:
      - HARVESTERAI_DATA_DIR=/data
      - AUTH_MODE=login
      - AUTH_SECRET_KEY=change-this-to-a-long-random-secret
      - INITIAL_ADMIN_USER=admin
      - INITIAL_ADMIN_PASSWORD=changeme
      - SIGNUP_MODE=code
      - SIGNUP_CODE=code-to-make-a-new-account-goes-here

volumes:
  harvesterai_data:
